!#/bin/bash
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_1.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_2.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_3.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_12_1.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_12_2.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_12_3.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_12_1.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_12_2.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_12_3.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_13_1.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_13_2.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_13_3.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_2_1.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_2_2.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_2_3.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_8_1.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_8_2.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_8_3.json