!#/bin/bash
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_1.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_2.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_3.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_4.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_5.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_6.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_1.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_2.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_3.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_4.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_5.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_6.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_1.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_2.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_3.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_4.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_5.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_6.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_2_1.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_2_2.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_2_3.json
python main.py --config custom_configs/hyperparameter_search/lstm_configs/config_2_4.json