!#/bin/bash
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_1.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_3.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_4.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_6.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_7.json
python main.py --config custom_configs/hyperparameter_search/dnn_configs/config_10_9.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_1.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_2.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_3.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_4.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_5.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_6.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_7.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_8.json
python main.py --config custom_configs/hyperparameter_search/avg_seq_cls_configs/config_11_9.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_1.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_3.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_4.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_6.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_7.json
python main.py --config custom_configs/hyperparameter_search/fine_tune_configs/config_2_9.json